// Generated by BUCKLESCRIPT VERSION 2.0.1, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function hello(_, _$1, cb) {
  var tester = {
    statusCode: 200,
    body: {
      message: "Hello Body"
    }
  };
  console.log("*****************");
  return Curry._2(cb, null, tester);
}

exports.hello = hello;
/* No side effect */
